name: Bundle

on:
  push:
    branches:
      - main

jobs:
  bundle:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Install dependencies
        run: |
          pip install online-judge-verify-helper

      - name: Run oj-bundle
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          find src -name "*.hpp" | while read -r file; do
              out="expanded/${file#src/}"
              mkdir -p "$(dirname "$out")"
              oj-bundle "$file" > "$out"
          done

          if [ -n "$(git status --porcelain expanded)" ]; then
            git add expanded/
            git commit -m "Automated bundle"
            git push origin HEAD:${{ github.ref }}
          fi
